#configuration-as-code:
#  deprecated: "warn"
#  restricted: "warn"
#  unknown: "warn"

jenkins:
  systemMessage: | 
    Automatically configured(boostrapped) Jenkins docker instance. 
    When making changes to the system configuration consider if they should be part of the bootstrapping."

  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: true
  
  primaryView:
    all:
      name: "all"
  
  mode: NORMAL
  numExecutors: 2
  quietPeriod: 5
  scmCheckoutRetryCount: 1

  slaveAgentPort: 50000
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  
  views:
  - all:
      name: "all"
  
  globalNodeProperties:
    - envVars:
        env:
          - key: SONARQUBE_SERVER_NAME
            value: "http://sonarqube.local.net"
  
  # Security Configurations
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: ${JENKINS_ADMIN_USER}
        password: ${JENKINS_ADMIN_PASSWORD}

  crumbIssuer: 
    standard:
       excludeClientIPFromCrumb: false

  remotingSecurity:
    enabled: true
  
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: true
  
  disableRememberMe: true

tool:
  git:
    installations:
    - home: "/usr/bin/git"
      name: "Default"
  
  jdk:
    installations:
    - home: "/usr/local/openjdk-8"
      name: "openjdk-8"
  
  maven:
    installations:
    - home: "/usr/share/maven"
      name: "maven-3.3.9"

  msBuildSQRunnerInstallation:
    installations:
    - name: "sonar-scanner-net-core-2.0"
      home: ""
      properties:
      - installSource:
          installers:
          - msBuildSonarQubeRunnerInstaller:
              id: "5.0.4.24009-netcore"
          - msBuildSonarQubeRunnerInstaller:
              id: "5.0.4.24009"
  
  sonarRunnerInstallation:
    installations:
    - name: "sonar-scanner-4.5.0"
      home: ""
      properties:
      - installSource:
          installers:
          - sonarRunnerInstaller:
              id: "4.5.0.2216"

unclassified:
  location:
    url: http://jenkins.local.net

  sonarGlobalConfiguration:
    installations:
      - name: "sonarqube.local.net"
        serverUrl: "http://sonarqube.local.net"
        triggers:
          skipScmCause: true
          skipUpstreamCause: true

credentials:
  system:
    domainCredentials:
      - credentials:
        - usernamePassword:
            scope: GLOBAL
            id: "gtilab-root"
            username: "root"
            password: "${GITLAB_ROOT_PASSWORD}"
            description: "Username/Password Credentials for GitLab root. Used for cloning."
        - usernamePassword:
            scope: GLOBAL
            id: "sonar-jenkins"
            username: "jenkins"
            password: "${JENKINS_ADMIN_PASSWORD}"
            description: "Username/Password Credentials for SonarQube jenkins user."
        - gitLabApiTokenImpl:
            scope: GLOBAL
            id: "gitlab-token"
            apiToken: "{AQAAABAAAAAQPDjGtPG8R2Ka2/xVfl9Rnb4PqvQBWwuOX07USdb3v0E=}" # This is a dummy value and must be updated.
            description: "gitlab-token"
